---
- name: checking version
  hosts: lab
  connection: local
  gather_facts: no

  tasks:
  - name: run some commands and show the output
    eos_command:
      provider: '{{ eos_connection }}'
      commands:
         - command: show ip interface brief
           output: text
         - command: show running-config section Ethernet1\b
           output: text
         - show ip route
  tasks:
  - name: run some commands and show the output
    eos_command:
      provider: '{{ eos_connection }}'
      commands:
        - show version
    register: eos_output
  - debug: var=eos_output
