---
- hosts: lab #This is a reference to my group for all Spine/Leaf switches described in my Ansible hosts file.
  gather_facts: no
  connection: local #This sets the playbook to connect via the API using the details described in my .eapi.conf file.
  vars:
    modelName:  "{{ eos_output.stdout_lines[0].modelName }}"
    internalVersion: "{{ eos_output.stdout_lines[0].internalVersion }}"
    systemMacAddress: "{{ eos_output.stdout_lines[0].systemMacAddress }}"
  tasks:
    - name: execute show version
      eos_command:
        provider: '{{ eos_connection }}'
        commands:
          - show version
      register: eos_output
    - debug: var=eos_output
    - local_action: copy content={{ eos_output }} dest=/root/git/ansible-testing/eos_output
    - local_action: copy content={{ eos_output|to_json }} dest=/root/git/ansible-testing/eos_output_json
#    - name: "show only version"
#      debug: var=item
#      with_items: "{{ eos_output|to_json|from_json|json_query('stdout') }}"
#    - name: setting variables of Output
#      set_fact:
#        modelName:  "{{ eos_output|json_query('stdout.version') }}
#    - debug: msg= {{ modelName }}
#        internalVersion: "{{ eos_output.msg.stdout_lines.internalVersion }}"
    - name: output to template
      template: src=/root/git/ansible-testing/showversion/showver_output.j2 dest=/root/git/ansible-testing/showversion/testresults/{{ inventory_hostname }}.showveryam
