---
- name: checking version
  hosts: lab
  connection: local
  gather_facts: no
  vars:
    management_address: "{{ ansible_net_interfaces.Management1.ipv4.address }}"

  tasks:
    - name: gathering version from device
      eos_facts:
        provider:
          transport: eapi
          username: eos
          password: eos
          use_ssl: no
        gather_subset: all
      register: result
    - debug: var=ansible_net_interfaces
    - set_fact:
        fact1: "{{ ansible_net_hostname }}"
    - name: Display Hostname
      debug:
        msg: "{{fact1}}"
    - debug: var=management_address



#modelName:  "{{ eos_output.stdout_lines[0].modelName }}"
